# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: true

r:
 - release
 - devel
 
apt_packages:
 - default-jre
 - default-jdk
 
addons:
 apt:
  packages:
   - libnetcdf-dev
   - udunits-bin
   - libudunits2-dev

r_packages:
 - rlang
 - digest
 - devtools
 - covr
 - testthat
 
after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change