# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
bioc_required: true

apt_packages:
 - libnetcdf-dev
 - udunits-bin
 - libudunits2-dev
 
r_github_packages:
 - jasenfinch/binneR
 - jasenfinch/binneRlyse
 - jasenfinch/metaboData
 - jasenfinch/mzAnnotation
 - jasenfinch/MFassign
 - jasenfinch/profilePro
 - wilsontom/FIEmspro
 - jasenfinch/metabolyseR
 - jasenfinch/metaboWorkflows
 - jasenfinch/metaboVis

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change