language: R
sudo: true
cache: packages
warnings_are_errors: true

r:
- release
- devel

apt_packages:
- default-jre
- default-jdk

addons:
  apt:
    packages:
    - libnetcdf-dev
    - udunits-bin
    - libudunits2-dev
    
after_success:
- Rscript -e 'covr::codecov()'

notifications:
  email: false
  slack:
    secure: Q28IHJ94VriJPuNd6g8pjg70+uLqGL9jQSduMHWiwERXXyVupWmyYHKvTp3XwWj2r2Cuh6KLOF7i3RtFECUVt0bDZ3AmXN58jkg5DCFLvBtj8HILbea+1rerf7vrmE7Cc86lhN1aFy2/3DVwkNakvStE8BerYtzNr/p1xKDlT/DbItBjiapVSaGJaZpIfH5Qtxs3fps25OUktKkbeUgyqlEjtePcl4dnmLwFtDcD+6cTpf1qbVX7YaKX6VfrIUTuuR3m0Zdfdrtt5lc8kTo9U+M3/XiDizUsSgUYwSkZfXFIThTBIxL78jIXdp6Nnmb/lw95pFV9c6z7hw/MDBy58gFabdsAfyDOlTTgWb2orM6XlmZoTUGQJf1lmHJVdmLYK5efjZqvNFrxWrEHPVADWCV5jOC9CD+PD6y/YdpOb6vAIkhICnXCwoN5WEk45jya2f8M7eoukzPZvytWj7b+/XmOui8z5mmE0zjyztzEAJk84By3pJwcyYFA937cWdJYoCM/e/obe3kxp+V4dQ8PJShZJuzJsZYjdaisk7DRH3NBn6LhtSdPvTZbDwAjwH12UyEJsrMyIEeI9dX4pZnKZy3B7JQ32yiCRxPcM4jW64dlhFWyqUP50y0xw2QWuBcBAOpdTr2EuUSOVHkLsaVInJYQzi5tJ9BqQmgVpEMmpUI=
  on_success: change
  on_failure: change