# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
bioc_required: true
warnings_are_errors: true

addons:
 apt:
  packages:
   - maven
   - libnetcdf-dev
   - udunits-bin
   - libudunits2-dev

install: 
 - travis_wait 40 mvn install
 
after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change